import { createAdminClient } from '@/lib/supabase/admin'
import { createClient as createServerClient } from '@/lib/supabase/server'
import { Resend } from 'resend'
import { NextResponse } from 'next/server'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({}))
  const { email, name } = body

  if (!email) {
    return NextResponse.json({ error: 'email is required' }, { status: 400 })
  }

  // Get the admin's user ID from their session cookie
  const serverSupabase = await createServerClient()
  const { data: { user: adminUser } } = await serverSupabase.auth.getUser()
  if (!adminUser) {
    return NextResponse.json({ error: 'unauthorized' }, { status: 401 })
  }

  const admin = createAdminClient()

  // Insert invite row (token auto-generated by DB default)
  const { data: invite, error } = await admin
    .from('teacher_invites')
    .insert({ email, invited_by: adminUser.id })
    .select('token')
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  const inviteUrl = `${process.env.TEACHER_APP_URL}/invite?token=${invite.token}`

  await resend.emails.send({
    from: 'Parikshanam <admin@parikshanam.com>',
    to: email,
    subject: "You've been invited to teach on Parikshanam",
    html: `
      <h2>Hi ${name ?? 'there'},</h2>
      <p>You've been invited to join Parikshanam as a teacher.</p>
      <p><a href="${inviteUrl}" style="background:#E8720C;color:#fff;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:bold;">Accept Invitation</a></p>
      <p>This link expires in 7 days.</p>
    `,
  })

  return NextResponse.json({ ok: true })
}
